# Generated by Django 3.1.4 on 2020-12-19 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': 'Contact_Us'},
        ),
    ]
