# Generated by Django 3.1.4 on 2020-12-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201219_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_registered',
            field=models.BooleanField(null=True),
        ),
    ]
